SHOW USER;

DROP TABLE MEMBER;
CREATE TABLE MEMBER(
    MID NVARCHAR2(20) CONSTRAINT PK_MEMBER PRIMARY KEY,
    MPASSWORD NVARCHAR2(20) NOT NULL,
    MNAME NVARCHAR2(15) NOT NULL,
    MBIRTH DATE,
    MEMAIL NVARCHAR2(50),
    MADDRESS1 NVARCHAR2(50),
    MADDRESS2 NVARCHAR2(50),
    MADDRESS3 NVARCHAR2(50),
    MADDRESS4 NVARCHAR2(50),
    MPHONE NVARCHAR2(15),
    MFILENAME NVARCHAR2(100),
    KAKAOID NVARCHAR2(20),
    NAVERID NVARCHAR2(20));

-------------------------------------------------------------

DROP TABLE BOARD;
CREATE TABLE BOARD(
    BNUMBER NUMBER CONSTRAINT PK_BOARD PRIMARY KEY,
    BWRITER NVARCHAR2(20) CONSTRAINT FK_BOARD REFERENCES MEMBER(MID) on delete cascade,
    BTITLE NVARCHAR2(50) NOT NULL,
    BCONTENTS NVARCHAR2(500),
    BDATE DATE,
    BFILENAME NVARCHAR2(200),
    BHITS NUMBER);
    
drop sequence board_seq;
CREATE SEQUENCE BOARD_SEQ
    START WITH 1
    INCREMENT BY 1
    NOCACHE;

alter table board add (gdsThumbImg varchar(200));
------------------------------------------------------------

DROP TABLE BOARDCOMMENT;
CREATE TABLE BOARDCOMMENT(
    CNUMBER NUMBER CONSTRAINT PK_COMMENT PRIMARY KEY,
    BNUMBER NUMBER CONSTRAINT FK_COMMENTBNUMBER REFERENCES BOARD(BNUMBER) on delete cascade,
    CWRITER NVARCHAR2(20) CONSTRAINT FK_COMMENTMID REFERENCES MEMBER(MID) on delete cascade,
    CCONTENTS NVARCHAR2(200),
    CDATE DATE);
    
SELECT * FROM MEMBER;
SELECT * FROM BOARD;
SELECT * FROM BOARDCOMMENT;
select * from comment_seq;

drop sequence comment_seq;
CREATE SEQUENCE COMMENT_SEQ
    START WITH 1
    INCREMENT BY 1
    NOCACHE;
    
commit;